import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./Component/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-gradient-to-r from-indigo-500 via-purple-500 to-pink-500 flex flex-col items-center jusitify-center text-white w-full min-h-screen mx-auto`}>
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
